language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - mysql -e 'create database travis;'
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist

addons:
  mariadb: '10.0'