language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - cp .env.travis .env
  - mysql -e 'create database travis;'
  - travis_retry composer self-update
  - php artisan migrate

install:
  - travis_retry composer install --no-interaction --prefer-dist

addons:
  mariadb: '10.1'